// <auto-generated />
using System;
using Cinomni.Subtitles.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Subtitles.Persistence.Migrations
{
    [DbContext(typeof(SubtitlesDbContext))]
    [Migration("20260728070824_InitialSubtitles")]
    partial class InitialSubtitles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("subtitles")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Subtitles.Persistence.SubtitleAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Forced")
                        .HasColumnType("boolean")
                        .HasColumnName("forced");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<bool>("HearingImpaired")
                        .HasColumnType("boolean")
                        .HasColumnName("hearing_impaired");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("path");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_id");

                    b.HasKey("Id")
                        .HasName("pk_subtitle_assets");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_subtitle_assets_asset_id");

                    b.ToTable("subtitle_assets", "subtitles");
                });

            modelBuilder.Entity("Cinomni.Subtitles.Persistence.SubtitleCandidate", b =>
                {
                    b.Property<Guid>("SearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("DownloadRef")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("download_ref");

                    b.Property<bool>("HearingImpaired")
                        .HasColumnType("boolean")
                        .HasColumnName("hearing_impaired");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<string>("Release")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("release");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("SearchId", "Seq")
                        .HasName("pk_subtitle_candidates");

                    b.ToTable("subtitle_candidates", "subtitles");
                });

            modelBuilder.Entity("Cinomni.Subtitles.Persistence.SubtitleSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Forced")
                        .HasColumnType("boolean")
                        .HasColumnName("forced");

                    b.Property<bool>("HearingImpaired")
                        .HasColumnType("boolean")
                        .HasColumnName("hearing_impaired");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid?>("SubtitleAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("subtitle_asset_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subtitle_searches");

                    b.HasIndex("AssetId", "Language", "Forced", "HearingImpaired")
                        .IsUnique()
                        .HasDatabaseName("ux_subtitle_searches_asset_language");

                    b.ToTable("subtitle_searches", "subtitles");
                });

            modelBuilder.Entity("Cinomni.Subtitles.Persistence.SubtitleCandidate", b =>
                {
                    b.HasOne("Cinomni.Subtitles.Persistence.SubtitleSearch", null)
                        .WithMany("Candidates")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subtitle_candidates_subtitle_searches_search_id");
                });

            modelBuilder.Entity("Cinomni.Subtitles.Persistence.SubtitleSearch", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
