// <auto-generated />
using System;
using System.Collections.Generic;
using Cinomni.Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260902184027_AddWorkGenresAndContentRating")]
    partial class AddWorkGenresAndContentRating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("access_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_collections_default")
                        .HasFilter("is_default");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_collections_name");

                    b.ToTable("collections", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.CollectionGrant", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.HasKey("CollectionId", "UserId")
                        .HasName("pk_collection_grants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_collection_grants_user");

                    b.ToTable("collection_grants", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AbsoluteNumber")
                        .HasColumnType("integer")
                        .HasColumnName("absolute_number");

                    b.Property<bool>("AbsoluteNumberIsDerived")
                        .HasColumnType("boolean")
                        .HasColumnName("absolute_number_is_derived");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date")
                        .HasColumnName("air_date");

                    b.Property<DateTimeOffset?>("AirDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("air_date_time");

                    b.Property<bool>("HasAsset")
                        .HasColumnType("boolean")
                        .HasColumnName("has_asset");

                    b.Property<Guid?>("MetadataSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("metadata_snapshot_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<string>("StillUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("still_url");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_episodes");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_episodes_season_id");

                    b.HasIndex("WorkId", "AbsoluteNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_episodes_work_absolute_number")
                        .HasFilter("absolute_number IS NOT NULL");

                    b.HasIndex("WorkId", "AirDate")
                        .HasDatabaseName("ix_episodes_work_air_date");

                    b.HasIndex("WorkId", "SeasonNumber", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_episodes_work_season_number");

                    b.ToTable("episodes", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.ExternalIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_external_identifiers");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_external_identifiers_work_id");

                    b.HasIndex("Provider", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identifiers_provider_value");

                    b.ToTable("external_identifiers", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date")
                        .HasColumnName("air_date");

                    b.Property<int?>("ExpectedEpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("expected_episode_count");

                    b.Property<Guid?>("MetadataSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("metadata_snapshot_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("poster_url");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("WorkId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_seasons_work_number");

                    b.ToTable("seasons", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("AvailableEpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("available_episode_count");

                    b.Property<string>("BackdropUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("backdrop_url");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("ContentRating")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_rating");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("integer")
                        .HasColumnName("episode_count");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("genres")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<bool>("HasAsset")
                        .HasColumnType("boolean")
                        .HasColumnName("has_asset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MetadataSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("metadata_snapshot_id");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_language");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("poster_url");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sort_title");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StructureProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("structure_provider");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("SortTitle")
                        .HasDatabaseName("ix_works_sort_title");

                    b.HasIndex("CollectionId", "SortTitle")
                        .HasDatabaseName("ix_works_collection_sort_title");

                    b.ToTable("works", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.CollectionGrant", b =>
                {
                    b.HasOne("Cinomni.Catalog.Persistence.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_grants_collections_collection_id");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Episode", b =>
                {
                    b.HasOne("Cinomni.Catalog.Persistence.Season", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_episodes_seasons_season_id");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.ExternalIdentifier", b =>
                {
                    b.HasOne("Cinomni.Catalog.Persistence.Work", null)
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identifiers_works_work_id");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Season", b =>
                {
                    b.HasOne("Cinomni.Catalog.Persistence.Work", null)
                        .WithMany("Seasons")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seasons_works_work_id");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Work", b =>
                {
                    b.HasOne("Cinomni.Catalog.Persistence.Collection", null)
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_collections_collection_id");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Work", b =>
                {
                    b.Navigation("ExternalIdentifiers");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
