// <auto-generated />
using System;
using Cinomni.Catalog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260728120925_AddWorkMetadataSnapshot")]
    partial class AddWorkMetadataSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Catalog.Persistence.ExternalIdentifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_external_identifiers");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_external_identifiers_work_id");

                    b.HasIndex("Provider", "Value")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identifiers_provider_value");

                    b.ToTable("external_identifiers", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool>("HasAsset")
                        .HasColumnType("boolean")
                        .HasColumnName("has_asset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MetadataSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("metadata_snapshot_id");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("original_language");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("runtime_minutes");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sort_title");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("SortTitle")
                        .HasDatabaseName("ix_works_sort_title");

                    b.ToTable("works", "catalog");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.ExternalIdentifier", b =>
                {
                    b.HasOne("Cinomni.Catalog.Persistence.Work", null)
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identifiers_works_work_id");
                });

            modelBuilder.Entity("Cinomni.Catalog.Persistence.Work", b =>
                {
                    b.Navigation("ExternalIdentifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
