// <auto-generated />
using System;
using Cinomni.Discovery.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Discovery.Persistence.Migrations
{
    [DbContext(typeof(DiscoveryDbContext))]
    [Migration("20260901233735_AddIndexerSessions")]
    partial class AddIndexerSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discovery")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Discovery.Persistence.Indexer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("base_url");

                    b.Property<string>("CatalogKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalog_key");

                    b.Property<int?>("CatalogVersion")
                        .HasColumnType("integer")
                        .HasColumnName("catalog_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_username");

                    b.Property<Guid?>("DefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("definition_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int?>("GrabLimit")
                        .HasColumnType("integer")
                        .HasColumnName("grab_limit");

                    b.Property<string>("LastTestCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_test_code");

                    b.Property<string>("LastTestMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_test_message");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("boolean")
                        .HasColumnName("last_test_succeeded");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_tested_at");

                    b.Property<string>("LimitsUnit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Day")
                        .HasColumnName("limits_unit");

                    b.Property<int?>("MinimumSeeders")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_seeders");

                    b.Property<string>("MovieCategories")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("movie_categories");

                    b.Property<string>("MovieSearchParams")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("movie_search_params");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("PreferMagnet")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_magnet");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocol");

                    b.Property<int?>("QueryLimit")
                        .HasColumnType("integer")
                        .HasColumnName("query_limit");

                    b.Property<byte[]>("SecretCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("secret_cipher");

                    b.Property<string>("SecretKeyId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("secret_key_id");

                    b.Property<byte[]>("SecretNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("secret_nonce");

                    b.Property<bool>("SupportsMovieSearch")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_movie_search");

                    b.Property<bool>("SupportsTvSearch")
                        .HasColumnType("boolean")
                        .HasColumnName("supports_tv_search");

                    b.Property<string>("TvCategories")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tv_categories");

                    b.Property<string>("TvSearchParams")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tv_search_params");

                    b.Property<bool>("UseFlareSolverr")
                        .HasColumnType("boolean")
                        .HasColumnName("use_flare_solverr");

                    b.HasKey("Id")
                        .HasName("pk_indexers");

                    b.HasIndex("CatalogKey")
                        .IsUnique()
                        .HasDatabaseName("ix_indexers_catalog_key");

                    b.HasIndex("DefinitionId")
                        .HasDatabaseName("ix_indexers_definition_id");

                    b.HasIndex("Enabled", "Priority")
                        .HasDatabaseName("ix_indexers_enabled_priority");

                    b.ToTable("indexers", "discovery", t =>
                        {
                            t.HasCheckConstraint("ck_indexers_grab_limit", "grab_limit IS NULL OR grab_limit > 0");

                            t.HasCheckConstraint("ck_indexers_minimum_seeders", "minimum_seeders IS NULL OR minimum_seeders >= 0");

                            t.HasCheckConstraint("ck_indexers_query_limit", "query_limit IS NULL OR query_limit > 0");

                            t.HasCheckConstraint("ck_indexers_secret_cipher_with_nonce", "(secret_cipher IS NULL) = (secret_nonce IS NULL)");
                        });
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.IndexerDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("raw_content");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_indexer_definitions");

                    b.ToTable("indexer_definitions", "discovery");
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.IndexerSession", b =>
                {
                    b.Property<Guid>("IndexerId")
                        .HasColumnType("uuid")
                        .HasColumnName("indexer_id");

                    b.Property<DateTimeOffset?>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<byte[]>("CookiesCipher")
                        .HasColumnType("bytea")
                        .HasColumnName("cookies_cipher");

                    b.Property<string>("CookiesKeyId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cookies_key_id");

                    b.Property<byte[]>("CookiesNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("cookies_nonce");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<bool>("LastAttemptOk")
                        .HasColumnType("boolean")
                        .HasColumnName("last_attempt_ok");

                    b.HasKey("IndexerId")
                        .HasName("pk_indexer_sessions");

                    b.ToTable("indexer_sessions", "discovery", t =>
                        {
                            t.HasCheckConstraint("ck_indexer_sessions_cookies_cipher_with_nonce", "(cookies_cipher IS NULL) = (cookies_nonce IS NULL) AND (cookies_cipher IS NULL) = (cookies_key_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.IndexerUsage", b =>
                {
                    b.Property<Guid>("IndexerId")
                        .HasColumnType("uuid")
                        .HasColumnName("indexer_id");

                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date")
                        .HasColumnName("usage_date");

                    b.Property<int>("GrabCount")
                        .HasColumnType("integer")
                        .HasColumnName("grab_count");

                    b.Property<int>("QueryCount")
                        .HasColumnType("integer")
                        .HasColumnName("query_count");

                    b.HasKey("IndexerId", "UsageDate")
                        .HasName("pk_indexer_usage");

                    b.ToTable("indexer_usage", "discovery");
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.SearchExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int?>("AbsoluteNumber")
                        .HasColumnType("integer")
                        .HasColumnName("absolute_number");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date")
                        .HasColumnName("air_date");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("content_kind");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("imdb_id");

                    b.PrimitiveCollection<Guid[]>("RequestedUnitIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("requested_unit_ids");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("term");

                    b.Property<string>("TvdbId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tvdb_id");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id", "StartedAt")
                        .HasName("pk_search_executions");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_search_executions_started_at");

                    b.ToTable("search_executions", "discovery");
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.SearchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("found_at");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("download_url");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("execution_id");

                    b.Property<string>("IndexerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("indexer_name");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ReleaseGuid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_guid");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<int?>("Seeders")
                        .HasColumnType("integer")
                        .HasColumnName("seeders");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<string>("TvdbId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tvdb_id");

                    b.HasKey("Id", "FoundAt")
                        .HasName("pk_search_results");

                    b.HasIndex("ExecutionId")
                        .HasDatabaseName("ix_search_results_execution_id");

                    b.ToTable("search_results", "discovery");
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.Indexer", b =>
                {
                    b.HasOne("Cinomni.Discovery.Persistence.IndexerDefinition", null)
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_indexers_indexer_definitions_definition_id");
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.IndexerSession", b =>
                {
                    b.HasOne("Cinomni.Discovery.Persistence.Indexer", null)
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_indexer_sessions_indexers_indexer_id");
                });

            modelBuilder.Entity("Cinomni.Discovery.Persistence.IndexerUsage", b =>
                {
                    b.HasOne("Cinomni.Discovery.Persistence.Indexer", null)
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_indexer_usage_indexers_indexer_id");
                });
#pragma warning restore 612, 618
        }
    }
}
