// <auto-generated />
using System;
using Cinomni.Playback.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Playback.Persistence.Migrations
{
    [DbContext(typeof(PlaybackDbContext))]
    [Migration("20260728212033_AddSessionWorkId")]
    partial class AddSessionWorkId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("playback")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Playback.Persistence.PlaybackProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int?>("AudioStreamIndex")
                        .HasColumnType("integer")
                        .HasColumnName("audio_stream_index");

                    b.Property<int>("PlayCount")
                        .HasColumnType("integer")
                        .HasColumnName("play_count");

                    b.Property<bool>("Played")
                        .HasColumnType("boolean")
                        .HasColumnName("played");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("position_ticks");

                    b.Property<int?>("SubtitleStreamIndex")
                        .HasColumnType("integer")
                        .HasColumnName("subtitle_stream_index");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "AssetId")
                        .HasName("pk_playback_progress");

                    b.ToTable("playback_progress", "playback");
                });

            modelBuilder.Entity("Cinomni.Playback.Persistence.PlaybackSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int?>("AudioStreamIndex")
                        .HasColumnType("integer")
                        .HasColumnName("audio_stream_index");

                    b.Property<string>("Container")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("container");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ticks");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("full_path");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("method");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("plan_json");

                    b.Property<string>("PlaySessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("play_session_id");

                    b.Property<long>("PositionTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("position_ticks");

                    b.Property<int>("ProgressSeq")
                        .HasColumnType("integer")
                        .HasColumnName("progress_seq");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<int?>("SubtitleStreamIndex")
                        .HasColumnType("integer")
                        .HasColumnName("subtitle_stream_index");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_playback_sessions");

                    b.HasIndex("UserId", "AssetId")
                        .HasDatabaseName("ix_playback_sessions_user_asset");

                    b.ToTable("playback_sessions", "playback");
                });

            modelBuilder.Entity("Cinomni.Playback.Persistence.TranscodeJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Hls")
                        .HasColumnType("boolean")
                        .HasColumnName("hls");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("output_path");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("TargetAudioCodec")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_audio_codec");

                    b.Property<string>("TargetVideoCodec")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("target_video_codec");

                    b.HasKey("Id")
                        .HasName("pk_transcode_jobs");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_transcode_jobs_session_id");

                    b.ToTable("transcode_jobs", "playback");
                });

            modelBuilder.Entity("Cinomni.Playback.Persistence.TranscodeJob", b =>
                {
                    b.HasOne("Cinomni.Playback.Persistence.PlaybackSession", null)
                        .WithMany("TranscodeJobs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transcode_jobs_playback_sessions_session_id");
                });

            modelBuilder.Entity("Cinomni.Playback.Persistence.PlaybackSession", b =>
                {
                    b.Navigation("TranscodeJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
