// <auto-generated />
using System;
using Cinomni.Acquisition.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Acquisition.Persistence.Migrations
{
    [DbContext(typeof(AcquisitionDbContext))]
    [Migration("20260923210903_RecordAttemptRelease")]
    partial class RecordAttemptRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acquisition")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("download_url");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IndexerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("indexer_name");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<int?>("Leechers")
                        .HasColumnType("integer")
                        .HasColumnName("leechers");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("ReleaseGuid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_guid");

                    b.Property<string>("ReleaseTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_title");

                    b.Property<int?>("Seeders")
                        .HasColumnType("integer")
                        .HasColumnName("seeders");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_acquisition_attempts");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_acquisition_attempts_intent_id");

                    b.HasIndex("IntentId", "EvaluationId")
                        .IsUnique()
                        .HasDatabaseName("ix_acquisition_attempts_intent_evaluation");

                    b.ToTable("acquisition_attempts", "acquisition");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionAttemptUnit", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("AttemptId", "UnitId")
                        .HasName("pk_acquisition_attempt_units");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_acquisition_attempt_units_unit_id");

                    b.ToTable("acquisition_attempt_units", "acquisition");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionHistoryRecord", b =>
                {
                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger");

                    b.HasKey("IntentId", "Seq")
                        .HasName("pk_acquisition_history");

                    b.ToTable("acquisition_history", "acquisition");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastFailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_failure_reason");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<string>("SelectedReleaseGuid")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("selected_release_guid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_acquisition_intents");

                    b.HasIndex("TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_acquisition_intents_target_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_acquisition_intents_unit_id");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_acquisition_intents_work_id");

                    b.ToTable("acquisition_intents", "acquisition");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionAttempt", b =>
                {
                    b.HasOne("Cinomni.Acquisition.Persistence.AcquisitionIntent", null)
                        .WithMany("Attempts")
                        .HasForeignKey("IntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acquisition_attempts_acquisition_intents_intent_id");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionAttemptUnit", b =>
                {
                    b.HasOne("Cinomni.Acquisition.Persistence.AcquisitionAttempt", null)
                        .WithMany("Units")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acquisition_attempt_units_acquisition_attempts_attempt_id");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionHistoryRecord", b =>
                {
                    b.HasOne("Cinomni.Acquisition.Persistence.AcquisitionIntent", null)
                        .WithMany("History")
                        .HasForeignKey("IntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acquisition_history_acquisition_intents_intent_id");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionAttempt", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Cinomni.Acquisition.Persistence.AcquisitionIntent", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
