// <auto-generated />
using System;
using Cinomni.Decision.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Decision.Persistence.Migrations
{
    [DbContext(typeof(DecisionDbContext))]
    partial class DecisionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("decision")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Decision.Persistence.AcquisitionProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("applies_to");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CutoffRank")
                        .HasColumnType("integer")
                        .HasColumnName("cutoff_rank");

                    b.Property<int>("MinFormatScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_format_score");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("UpgradesAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("upgrades_allowed");

                    b.HasKey("Id")
                        .HasName("pk_acquisition_profiles");

                    b.HasIndex("AppliesTo")
                        .HasDatabaseName("ix_acquisition_profiles_applies_to");

                    b.ToTable("acquisition_profiles", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.AllowedQuality", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("MaxSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("max_size_bytes");

                    b.Property<long?>("MinSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("min_size_bytes");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resolution");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_allowed_qualities");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_allowed_qualities_profile_id");

                    b.ToTable("allowed_qualities", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.DecisionReasonRecord", b =>
                {
                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluation_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("ActualValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actual_value");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("outcome");

                    b.Property<string>("ProfileValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("profile_value");

                    b.Property<string>("Property")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property");

                    b.Property<string>("Rejection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("rejection");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule");

                    b.HasKey("EvaluationId", "Seq")
                        .HasName("pk_decision_reasons");

                    b.ToTable("decision_reasons", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.FormatCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Negate")
                        .HasColumnType("boolean")
                        .HasColumnName("negate");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_format_conditions");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_format_conditions_rule_id");

                    b.ToTable("format_conditions", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.FormatRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("Negate")
                        .HasColumnType("boolean")
                        .HasColumnName("negate");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_format_rules");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_format_rules_profile_id");

                    b.ToTable("format_rules", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.ReleaseBlockRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReleaseGuid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_guid");

                    b.Property<string>("ReleaseTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("release_title");

                    b.HasKey("Id")
                        .HasName("pk_release_blocks");

                    b.HasIndex("ReleaseGuid")
                        .IsUnique()
                        .HasDatabaseName("ix_release_blocks_release_guid");

                    b.ToTable("release_blocks", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.ReleaseEvaluationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomFormatScore")
                        .HasColumnType("integer")
                        .HasColumnName("custom_format_score");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("evaluator_version");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("ReleaseGuid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_guid");

                    b.Property<string>("ReleaseTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("release_title");

                    b.Property<Guid>("SearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_id");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_release_evaluations");

                    b.HasIndex("SearchId")
                        .HasDatabaseName("ix_release_evaluations_search_id");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_release_evaluations_target_id");

                    b.HasIndex("Verdict", "CreatedAt")
                        .HasDatabaseName("ix_release_evaluations_purge");

                    b.ToTable("release_evaluations", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.TargetReleaseExclusionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ReleaseGuid")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("release_guid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_target_release_exclusions");

                    b.HasIndex("TargetId", "ReleaseGuid")
                        .IsUnique()
                        .HasDatabaseName("ux_target_release_exclusions_target_release");

                    b.ToTable("target_release_exclusions", "decision");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.AllowedQuality", b =>
                {
                    b.HasOne("Cinomni.Decision.Persistence.AcquisitionProfile", null)
                        .WithMany("AllowedQualities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_allowed_qualities_acquisition_profiles_profile_id");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.DecisionReasonRecord", b =>
                {
                    b.HasOne("Cinomni.Decision.Persistence.ReleaseEvaluationRecord", null)
                        .WithMany("Reasons")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decision_reasons_release_evaluations_evaluation_id");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.FormatCondition", b =>
                {
                    b.HasOne("Cinomni.Decision.Persistence.FormatRule", null)
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_format_conditions_format_rules_rule_id");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.FormatRule", b =>
                {
                    b.HasOne("Cinomni.Decision.Persistence.AcquisitionProfile", null)
                        .WithMany("FormatRules")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_format_rules_acquisition_profiles_profile_id");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.AcquisitionProfile", b =>
                {
                    b.Navigation("AllowedQualities");

                    b.Navigation("FormatRules");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.FormatRule", b =>
                {
                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("Cinomni.Decision.Persistence.ReleaseEvaluationRecord", b =>
                {
                    b.Navigation("Reasons");
                });
#pragma warning restore 612, 618
        }
    }
}
