// <auto-generated />
using System;
using Cinomni.Downloads.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Downloads.Persistence.Migrations
{
    [DbContext(typeof(DownloadsDbContext))]
    [Migration("20260923122151_TrackTransferProgress")]
    partial class TrackTransferProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("downloads")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadHistoryRecord", b =>
                {
                    b.Property<Guid>("DownloadTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("download_task_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger");

                    b.HasKey("DownloadTaskId", "Seq")
                        .HasName("pk_download_history");

                    b.ToTable("download_history", "downloads");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AllTimeDownload")
                        .HasColumnType("bigint")
                        .HasColumnName("all_time_download");

                    b.Property<long>("AllTimeUpload")
                        .HasColumnType("bigint")
                        .HasColumnName("all_time_upload");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<double>("BestProgress")
                        .HasColumnType("double precision")
                        .HasColumnName("best_progress");

                    b.Property<int>("CheckpointSeq")
                        .HasColumnType("integer")
                        .HasColumnName("checkpoint_seq");

                    b.Property<string>("ContentPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("content_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DownloadRate")
                        .HasColumnType("bigint")
                        .HasColumnName("download_rate");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("download_url");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("info_hash");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastProgressAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_progress_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("NetworkHoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("network_hold_reason");

                    b.Property<DateTimeOffset?>("NetworkHoldSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("network_hold_since");

                    b.Property<int>("NumPeers")
                        .HasColumnType("integer")
                        .HasColumnName("num_peers");

                    b.Property<int>("NumSeeds")
                        .HasColumnType("integer")
                        .HasColumnName("num_seeds");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision")
                        .HasColumnName("progress");

                    b.Property<string>("ReleaseGuid")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("release_guid");

                    b.Property<byte[]>("ResumeData")
                        .HasColumnType("bytea")
                        .HasColumnName("resume_data");

                    b.Property<string>("SavePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("save_path");

                    b.Property<string>("SeedingPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("seeding_policy_json");

                    b.Property<int>("SeedingSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("seeding_seconds");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UploadRate")
                        .HasColumnType("bigint")
                        .HasColumnName("upload_rate");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_download_tasks");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ix_download_tasks_attempt_id");

                    b.HasIndex("InfoHash")
                        .HasDatabaseName("ix_download_tasks_info_hash");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_download_tasks_intent_id");

                    b.HasIndex("NetworkHoldSince")
                        .HasDatabaseName("ix_download_tasks_network_hold")
                        .HasFilter("network_hold_since IS NOT NULL");

                    b.HasIndex("State", "UpdatedAt")
                        .HasDatabaseName("ix_download_tasks_checkpoint_trim")
                        .HasFilter("resume_data IS NOT NULL");

                    b.ToTable("download_tasks", "downloads");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadTaskClaim", b =>
                {
                    b.Property<Guid>("DownloadTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("download_task_id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<bool>("IsOriginating")
                        .HasColumnType("boolean")
                        .HasColumnName("is_originating");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("DownloadTaskId", "AttemptId")
                        .HasName("pk_download_task_claims");

                    b.HasIndex("AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ux_download_task_claims_attempt_id");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_download_task_claims_intent_id");

                    b.ToTable("download_task_claims", "downloads");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadTaskUnit", b =>
                {
                    b.Property<Guid>("DownloadTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("download_task_id");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("DownloadTaskId", "UnitId")
                        .HasName("pk_download_task_units");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_download_task_units_unit_id");

                    b.ToTable("download_task_units", "downloads");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.TorrentFile", b =>
                {
                    b.Property<Guid>("DownloadTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("download_task_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("path");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("DownloadTaskId", "Index")
                        .HasName("pk_torrent_files");

                    b.ToTable("torrent_files", "downloads");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.TunnelStateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Holding")
                        .HasColumnType("boolean")
                        .HasColumnName("holding");

                    b.Property<DateTimeOffset?>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<int>("TransitionSequence")
                        .HasColumnType("integer")
                        .HasColumnName("transition_sequence");

                    b.Property<string>("TunnelDevice")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tunnel_device");

                    b.Property<int>("UnverifiedStreak")
                        .HasColumnType("integer")
                        .HasColumnName("unverified_streak");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<int>("VerifiedStreak")
                        .HasColumnType("integer")
                        .HasColumnName("verified_streak");

                    b.HasKey("Id")
                        .HasName("pk_tunnel_state");

                    b.ToTable("tunnel_state", "downloads");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadHistoryRecord", b =>
                {
                    b.HasOne("Cinomni.Downloads.Persistence.DownloadTask", null)
                        .WithMany("History")
                        .HasForeignKey("DownloadTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_download_history_download_tasks_download_task_id");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadTaskClaim", b =>
                {
                    b.HasOne("Cinomni.Downloads.Persistence.DownloadTask", null)
                        .WithMany("Claims")
                        .HasForeignKey("DownloadTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_download_task_claims_download_tasks_download_task_id");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadTaskUnit", b =>
                {
                    b.HasOne("Cinomni.Downloads.Persistence.DownloadTask", null)
                        .WithMany("Units")
                        .HasForeignKey("DownloadTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_download_task_units_download_tasks_download_task_id");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.TorrentFile", b =>
                {
                    b.HasOne("Cinomni.Downloads.Persistence.DownloadTask", null)
                        .WithMany("Files")
                        .HasForeignKey("DownloadTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_torrent_files_download_tasks_download_task_id");
                });

            modelBuilder.Entity("Cinomni.Downloads.Persistence.DownloadTask", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Files");

                    b.Navigation("History");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
