// <auto-generated />
using System;
using Cinomni.Import.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Import.Persistence.Migrations
{
    [DbContext(typeof(ImportDbContext))]
    [Migration("20260728195855_AddImportFileMatches")]
    partial class AddImportFileMatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("import")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Import.Persistence.FileOperation", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("FromPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("from_path");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("ToPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("to_path");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("ImportJobId", "Seq")
                        .HasName("pk_file_operations");

                    b.ToTable("file_operations", "import");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.ImportFileMatch", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.PrimitiveCollection<int[]>("EpisodeNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("episode_numbers");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash");

                    b.Property<string>("MediaInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("media_info_json");

                    b.Property<int?>("OperationSeq")
                        .HasColumnType("integer")
                        .HasColumnName("operation_seq");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_path");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<string>("TargetPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_path");

                    b.PrimitiveCollection<Guid[]>("UnitIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("unit_ids");

                    b.HasKey("ImportJobId", "Seq")
                        .HasName("pk_import_file_matches");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_import_file_matches_asset_id");

                    b.ToTable("import_file_matches", "import");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.ImportHistoryRecord", b =>
                {
                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("trigger");

                    b.HasKey("ImportJobId", "Seq")
                        .HasName("pk_import_history");

                    b.ToTable("import_history", "import");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DownloadTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("download_task_id");

                    b.Property<Guid>("IntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("intent_id");

                    b.Property<string>("MatchedFileHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("matched_file_hash");

                    b.Property<string>("MatchedFilePath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("matched_file_path");

                    b.Property<long>("MatchedFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("matched_file_size");

                    b.Property<string>("MediaInfoJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("media_info_json");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_path");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("DownloadTaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_import_jobs_download_task_id");

                    b.HasIndex("IntentId")
                        .HasDatabaseName("ix_import_jobs_intent_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_import_jobs_state");

                    b.ToTable("import_jobs", "import");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.FileOperation", b =>
                {
                    b.HasOne("Cinomni.Import.Persistence.ImportJob", null)
                        .WithMany("Operations")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_file_operations_import_jobs_import_job_id");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.ImportFileMatch", b =>
                {
                    b.HasOne("Cinomni.Import.Persistence.ImportJob", null)
                        .WithMany("Matches")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_file_matches_import_jobs_import_job_id");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.ImportHistoryRecord", b =>
                {
                    b.HasOne("Cinomni.Import.Persistence.ImportJob", null)
                        .WithMany("History")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_history_import_jobs_import_job_id");
                });

            modelBuilder.Entity("Cinomni.Import.Persistence.ImportJob", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Matches");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
