// <auto-generated />
using System;
using Cinomni.ReleaseParsing.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.ReleaseParsing.Persistence.Migrations
{
    [DbContext(typeof(ReleaseParsingDbContext))]
    [Migration("20260729175629_AddParseRetentionIndex")]
    partial class AddParseRetentionIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parsing")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.ReleaseParsing.Persistence.ParseRuleVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.HasKey("Version")
                        .HasName("pk_parse_rule_versions");

                    b.ToTable("parse_rule_versions", "parsing");
                });

            modelBuilder.Entity("Cinomni.ReleaseParsing.Persistence.ParsedReleaseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AbsoluteEpisode")
                        .HasColumnType("integer")
                        .HasColumnName("absolute_episode");

                    b.Property<DateOnly?>("AirDate")
                        .HasColumnType("date")
                        .HasColumnName("air_date");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("edition");

                    b.Property<int?>("EpisodeFrom")
                        .HasColumnType("integer")
                        .HasColumnName("episode_from");

                    b.Property<int?>("EpisodeTo")
                        .HasColumnType("integer")
                        .HasColumnName("episode_to");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("info_hash");

                    b.Property<string>("LanguagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("languages_json");

                    b.Property<string>("NumberingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("numbering_json");

                    b.Property<string>("ParserVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parser_version");

                    b.Property<int?>("Part")
                        .HasColumnType("integer")
                        .HasColumnName("part");

                    b.Property<string>("QualityJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("quality_json");

                    b.Property<string>("ReleaseGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("release_group");

                    b.Property<string>("ReleaseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("release_type");

                    b.Property<string>("RevisionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("revision_json");

                    b.Property<int?>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<int?>("SeasonTo")
                        .HasColumnType("integer")
                        .HasColumnName("season_to");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_parsed_releases");

                    b.HasIndex("CanonicalKey")
                        .HasDatabaseName("ix_parsed_releases_canonical_key");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_parsed_releases_created_at");

                    b.HasIndex("Season", "EpisodeFrom")
                        .HasDatabaseName("ix_parsed_releases_season_episode");

                    b.ToTable("parsed_releases", "parsing");
                });
#pragma warning restore 612, 618
        }
    }
}
