// <auto-generated />
using System;
using Cinomni.Monitoring.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Monitoring.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260922133954_AddPublishedAirDateIndex")]
    partial class AddPublishedAirDateIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Monitoring.Persistence.MonitoredTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AbsoluteNumber")
                        .HasColumnType("integer")
                        .HasColumnName("absolute_number");

                    b.Property<Guid?>("AcquisitionProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("acquisition_profile_id");

                    b.Property<DateTimeOffset?>("AirDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("air_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<string>("EpisodeTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("episode_title");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_missing");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<DateTimeOffset?>("LastSearchRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_search_requested_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean")
                        .HasColumnName("monitored");

                    b.Property<Guid?>("ParentTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_target_id");

                    b.Property<DateOnly?>("PublishedAirDate")
                        .HasColumnType("date")
                        .HasColumnName("published_air_date");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<Guid>("TargetRef")
                        .HasColumnType("uuid")
                        .HasColumnName("target_ref");

                    b.Property<bool>("UpgradeWanted")
                        .HasColumnType("boolean")
                        .HasColumnName("upgrade_wanted");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_monitored_targets");

                    b.HasIndex("ParentTargetId")
                        .HasDatabaseName("ix_monitored_targets_parent");

                    b.HasIndex("PublishedAirDate")
                        .HasDatabaseName("ix_monitored_targets_published_air_date");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_monitored_targets_work_id");

                    b.HasIndex("Monitored", "IsMissing", "AirDate")
                        .HasDatabaseName("ix_monitored_targets_monitored_missing");

                    b.HasIndex("WorkId", "Kind", "TargetRef")
                        .IsUnique()
                        .HasDatabaseName("ux_monitored_targets_work_ref");

                    b.ToTable("monitored_targets", "monitoring");
                });
#pragma warning restore 612, 618
        }
    }
}
