// <auto-generated />
using System;
using Cinomni.Monitoring.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cinomni.Monitoring.Persistence.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260727170414_InitialMonitoring")]
    partial class InitialMonitoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cinomni.Monitoring.Persistence.MonitoredTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AcquisitionProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("acquisition_profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsMissing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_missing");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_evaluated_at");

                    b.Property<DateTimeOffset?>("LastSearchRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_search_requested_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean")
                        .HasColumnName("monitored");

                    b.Property<Guid>("TargetRef")
                        .HasColumnType("uuid")
                        .HasColumnName("target_ref");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_monitored_targets");

                    b.HasIndex("WorkId")
                        .IsUnique()
                        .HasDatabaseName("ux_monitored_targets_work_id");

                    b.HasIndex("Monitored", "IsMissing")
                        .HasDatabaseName("ix_monitored_targets_monitored_missing");

                    b.ToTable("monitored_targets", "monitoring");
                });
#pragma warning restore 612, 618
        }
    }
}
